<a href="https://colab.research.google.com/github/sunam128/Iris-Species-With-KNN./blob/main/IrisSpeciesWithKNN.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

In [2]:
ds=pd.read_csv("/content/Iris Data.csv")
ds.head()

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [3]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    object
dtypes: float64(4), object(1)
memory usage: 6.0+ KB

In [4]:
ds.isnull().sum()

sepal_length    0
sepal_width     0
petal_length    0
petal_width     0
species         0
dtype: int64

In [23]:
ds_reloaded = pd.read_csv("/content/Iris Data.csv")
y = ds_reloaded.pop('species')
x = ds_reloaded

In [24]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2)

In [25]:
classifier=KNeighborsClassifier(n_neighbors=5)

In [26]:
classifier.fit(x_train,y_train)

KNeighborsClassifier()

In [27]:
predictions=classifier.predict(x_test)

In [28]:
pd.DataFrame({'Actual':y_test,'Predicted':predictions})

              Actual        Predicted
120   Iris-virginica   Iris-virginica
67   Iris-versicolor  Iris-versicolor
9        Iris-setosa      Iris-setosa
92   Iris-versicolor  Iris-versicolor
60   Iris-versicolor  Iris-versicolor
8        Iris-setosa      Iris-setosa
106   Iris-virginica  Iris-versicolor
107   Iris-virginica   Iris-virginica
79   Iris-versicolor  Iris-versicolor
114   Iris-virginica   Iris-virginica
44       Iris-setosa      Iris-setosa
31       Iris-setosa      Iris-setosa
99   Iris-versicolor  Iris-versicolor
21       Iris-setosa      Iris-setosa
29       Iris-setosa      Iris-setosa
109   Iris-virginica   Iris-virginica
75   Iris-versicolor  Iris-versicolor
71   Iris-versicolor  Iris-versicolor
6        Iris-setosa      Iris-setosa
35       Iris-setosa      Iris-setosa
33       Iris-setosa      Iris-setosa
22       Iris-setosa      Iris-setosa
63   Iris-versicolor  Iris-versicolor
126   Iris-virginica   Iris-virginica
15       Iris-setosa      Iris-setosa
14       Iris-setosa      Iris-setosa
52   Iris-versicolor  Iris-versicolor
13       Iris-setosa      Iris-setosa
5        Iris-setosa      Iris-setosa
11       Iris-setosa      Iris-setosa

In [29]:
accuracy_score(y_test,predictions)

0.9666666666666667